baseURL = "https://ss-osanai.github.io/backnumber/"
languageCode = "ja-jp"
canonifyurls = true
publishDir = "docs"
title = 'バックナンバー'

defaultContentLanguage = "ja"
hasCJKLanguage = true

# theme = "minimal"
theme = "basic"

[Permalinks]
post = "/:sections/:contentbasename"
raw = "/:sections/:month/:contentbasename"
note = "/:sections/:month/:contentbasename"
x = "/:sections/:contentbasename"
transcription = "/:sections/:contentbasename"
X2 = "/:sections/:contentbasename"

[outputs]
home = ["HTML"]

[params]
# [[params.menu]]
# name = "post"
# url = "post/"

[[params.menu]]
name = "メルマガ"
url = "raw/"
[[params.menu]]
name = "メルマガ検索"
url = "search/"

[[params.menu]]
name = "X"
url = "x/posts"
[[params.menu]]
name = "X ハイライト"
url = "x/highlight_posts"
[[params.menu]]
name = "X ハイライト10万超"
url = "x/highlight_posts_100k_imp"

[[params.menu]]
name = "文字起こし"
url = "transcription/"

[[params.menu]]
name = "note"
url = "note/"

[[params.menu]]
name = "note検索"
url = "note_search/"

[services]
[services.googleAnalytics]
id = 'G-MEASUREMENT_ID'

[markup.goldmark.renderer]
unsafe = true
